name: Test
on: [push, pull_request]

jobs:
  short:
    runs-on: ubuntu-latest

    name: Node.js Quick
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: pnpm

      - name: Install dependencies
        run: pnpm ci:install

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test Build
        run: pnpm build

      - name: Run tests
        run: pnpm test
