name: Test
on: [push, pull_request]

jobs:
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20
          - 18
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
